name: "First Time Contributor Greeting"

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Greet first time contributors
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            👋 Thanks for opening your first issue! We appreciate your contribution to this project.
            
            A maintainer will review your issue and provide feedback soon. In the meantime, please make sure you've provided all the necessary information and checked if there are similar existing issues.
            
            Welcome to the community! 🎉
          pr-message: |
            🎉 Congratulations on your first pull request! We're excited to review your contribution.
            
            A maintainer will review your changes and provide feedback soon. Please make sure:
            - Your code follows the project's coding standards
            - All tests pass
            - You've updated documentation if needed
            
            Thank you for contributing! 🙌
